[[VTKMinimal]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "88b50e0d1797d480d0884df535ebfa1030f9a2ba"
libc = "glibc"
os = "linux"

    [[VTKMinimal.download]]
    sha256 = "bc087d1dd4cce423590d4481558aaaa143c67c927688081d53cc0b8ee4321f1f"
    url = "https://github.com/j-fu/VTKMinimal_jll.jl/releases/download/VTKMinimal-v8.2.0+1/VTKMinimal.v8.2.0.x86_64-linux-gnu-cxx11.tar.gz"
