[[VTKMinimal]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "f9c647c22eaf7e4f04562cbe3e1aacd237064f09"
libc = "glibc"
os = "linux"

    [[VTKMinimal.download]]
    sha256 = "c8c22005f8df9cafb95dfe042d9e1bc650bf69d8db735b255b7b071c8ccf6c0e"
    url = "https://github.com/j-fu/VTKMinimal_jll.jl/releases/download/VTKMinimal-v9.0.0+3/VTKMinimal.v9.0.0.aarch64-linux-gnu-cxx11.tar.gz"
[[VTKMinimal]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "b7e7040bc2d8ed17f559a8e456658bf33892b244"
libc = "glibc"
os = "linux"

    [[VTKMinimal.download]]
    sha256 = "da2a2340060b5574a210f684a069ffc1d93ab30fba018e053b6b3b8b0b490a6b"
    url = "https://github.com/j-fu/VTKMinimal_jll.jl/releases/download/VTKMinimal-v9.0.0+3/VTKMinimal.v9.0.0.i686-linux-gnu-cxx11.tar.gz"
[[VTKMinimal]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "f3910033a24ee6e1db460aba725f86b910256fc0"
libc = "musl"
os = "linux"

    [[VTKMinimal.download]]
    sha256 = "c156ee55d6a481337f20b46fb0016be608cdc12d7a30b70eb9297adc1b74baff"
    url = "https://github.com/j-fu/VTKMinimal_jll.jl/releases/download/VTKMinimal-v9.0.0+3/VTKMinimal.v9.0.0.aarch64-linux-musl-cxx11.tar.gz"
[[VTKMinimal]]
arch = "armv7l"
cxxstring_abi = "cxx11"
git-tree-sha1 = "6168aad54ced5c790f02066876dd5e04c574113d"
libc = "musl"
os = "linux"

    [[VTKMinimal.download]]
    sha256 = "1116493906d3475c5048f91036de3c66e972418536d518771340d010dba544d8"
    url = "https://github.com/j-fu/VTKMinimal_jll.jl/releases/download/VTKMinimal-v9.0.0+3/VTKMinimal.v9.0.0.armv7l-linux-musleabihf-cxx11.tar.gz"
[[VTKMinimal]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "30530af63db0509444e31393c72ff049dc7baa31"
libc = "musl"
os = "linux"

    [[VTKMinimal.download]]
    sha256 = "3c2d518eda2ba546bbd0b5e4e635569543b4b78fefce6726dbe5d3734c08dde9"
    url = "https://github.com/j-fu/VTKMinimal_jll.jl/releases/download/VTKMinimal-v9.0.0+3/VTKMinimal.v9.0.0.i686-linux-musl-cxx11.tar.gz"
[[VTKMinimal]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "e42e4b638fdf2fab9fe7bd943ba6e4c027a013fc"
libc = "musl"
os = "linux"

    [[VTKMinimal.download]]
    sha256 = "0426a5d27bdc1a6822db631663d4423c2461c00b14b435b89e8a5fa33e3b088c"
    url = "https://github.com/j-fu/VTKMinimal_jll.jl/releases/download/VTKMinimal-v9.0.0+3/VTKMinimal.v9.0.0.x86_64-linux-musl-cxx11.tar.gz"
[[VTKMinimal]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "22030271cbf80b483177e00fbb67939e2f5620d0"
libc = "glibc"
os = "linux"

    [[VTKMinimal.download]]
    sha256 = "f7ab94a9167d62dfd4870c84c869929bef86e8395e730853a9222afa7c1de04a"
    url = "https://github.com/j-fu/VTKMinimal_jll.jl/releases/download/VTKMinimal-v9.0.0+3/VTKMinimal.v9.0.0.x86_64-linux-gnu-cxx11.tar.gz"
[[VTKMinimal]]
arch = "armv7l"
cxxstring_abi = "cxx11"
git-tree-sha1 = "3077b9de051b092b4aee0134923f779352f937ca"
libc = "glibc"
os = "linux"

    [[VTKMinimal.download]]
    sha256 = "3ca4fcae17067035b49090bb663a03e97ab969820abe4dc91a7c76e41e6dd6af"
    url = "https://github.com/j-fu/VTKMinimal_jll.jl/releases/download/VTKMinimal-v9.0.0+3/VTKMinimal.v9.0.0.armv7l-linux-gnueabihf-cxx11.tar.gz"
[[VTKMinimal]]
arch = "powerpc64le"
cxxstring_abi = "cxx11"
git-tree-sha1 = "82486b862a02ca1b8c940a41153221f547802087"
libc = "glibc"
os = "linux"

    [[VTKMinimal.download]]
    sha256 = "d47776655a695bb682d84130d9933defb5e119c08474424fed7abea53c94c11c"
    url = "https://github.com/j-fu/VTKMinimal_jll.jl/releases/download/VTKMinimal-v9.0.0+3/VTKMinimal.v9.0.0.powerpc64le-linux-gnu-cxx11.tar.gz"
[[VTKMinimal]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "eb2a4dafbc9e194c597a4341ebb03a5a07cc1c55"
os = "freebsd"

    [[VTKMinimal.download]]
    sha256 = "879ded044e3f6e52db52fa13ac086b9002079c71426d88207bbdcd8c1915e06f"
    url = "https://github.com/j-fu/VTKMinimal_jll.jl/releases/download/VTKMinimal-v9.0.0+3/VTKMinimal.v9.0.0.x86_64-unknown-freebsd11.1-cxx11.tar.gz"
