[[VTKMinimal]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "5e16d3c192bb9857bd80ad7e651e62566fee06ee"
libc = "glibc"
os = "linux"

    [[VTKMinimal.download]]
    sha256 = "e5b7e654e65a92e77ffbd305b211abbc43ec453e220cd35caf646b55d4ea69d1"
    url = "https://github.com/j-fu/VTKMinimal_jll.jl/releases/download/VTKMinimal-v9.0.0+2/VTKMinimal.v9.0.0.aarch64-linux-gnu-cxx11.tar.gz"
[[VTKMinimal]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "ddae17f1eeb00f05e2d4d4f9994d484a89c1cac1"
libc = "glibc"
os = "linux"

    [[VTKMinimal.download]]
    sha256 = "974ef97a3f0b84b7b090b2ebe2d3a7c83eda15946b3a562641a8459200e0ab21"
    url = "https://github.com/j-fu/VTKMinimal_jll.jl/releases/download/VTKMinimal-v9.0.0+2/VTKMinimal.v9.0.0.i686-linux-gnu-cxx11.tar.gz"
[[VTKMinimal]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "35e608e4a276e61be0e1c06eb6014282527b707b"
libc = "musl"
os = "linux"

    [[VTKMinimal.download]]
    sha256 = "954f0669f11d3d3c72bfca9269a3794bed6f35368614531d636bdfd22f5326f8"
    url = "https://github.com/j-fu/VTKMinimal_jll.jl/releases/download/VTKMinimal-v9.0.0+2/VTKMinimal.v9.0.0.aarch64-linux-musl-cxx11.tar.gz"
[[VTKMinimal]]
arch = "armv7l"
cxxstring_abi = "cxx11"
git-tree-sha1 = "9d31584f6623eb3b744f4bac525fd742148bac02"
libc = "musl"
os = "linux"

    [[VTKMinimal.download]]
    sha256 = "f8821b72a78c25a6bac4e40a4bf3fa2eec809421f5c50f9872d49c760298d974"
    url = "https://github.com/j-fu/VTKMinimal_jll.jl/releases/download/VTKMinimal-v9.0.0+2/VTKMinimal.v9.0.0.armv7l-linux-musleabihf-cxx11.tar.gz"
[[VTKMinimal]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "58818eb5748f812a975c83742012ddafe2fe181d"
libc = "musl"
os = "linux"

    [[VTKMinimal.download]]
    sha256 = "0559e757da2f31e3a38812075c6acc4313245bba623499b1768d273356c20ad4"
    url = "https://github.com/j-fu/VTKMinimal_jll.jl/releases/download/VTKMinimal-v9.0.0+2/VTKMinimal.v9.0.0.i686-linux-musl-cxx11.tar.gz"
[[VTKMinimal]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "19d444a8fe03d20727d31bbb19f40c8601473829"
libc = "musl"
os = "linux"

    [[VTKMinimal.download]]
    sha256 = "58df8cf5634057bf7bff99bee440c49d159ad6efc2e5b9bb10e965f21361fa21"
    url = "https://github.com/j-fu/VTKMinimal_jll.jl/releases/download/VTKMinimal-v9.0.0+2/VTKMinimal.v9.0.0.x86_64-linux-musl-cxx11.tar.gz"
[[VTKMinimal]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "37a52f53fed5fbd99bc4512a48bd7101b7c76d22"
libc = "glibc"
os = "linux"

    [[VTKMinimal.download]]
    sha256 = "80e1a54543e08fe8b30ad907160d058486f09bdc9a8011a8f2c1b8ac92c77801"
    url = "https://github.com/j-fu/VTKMinimal_jll.jl/releases/download/VTKMinimal-v9.0.0+2/VTKMinimal.v9.0.0.x86_64-linux-gnu-cxx11.tar.gz"
[[VTKMinimal]]
arch = "armv7l"
cxxstring_abi = "cxx11"
git-tree-sha1 = "d05bbf44b82e8d161c77ce5081f6c0fd80f7f13b"
libc = "glibc"
os = "linux"

    [[VTKMinimal.download]]
    sha256 = "0245b38ca4ca465d268e3aa69eda25b8e9addc431b9ee4083b2269e840bf8329"
    url = "https://github.com/j-fu/VTKMinimal_jll.jl/releases/download/VTKMinimal-v9.0.0+2/VTKMinimal.v9.0.0.armv7l-linux-gnueabihf-cxx11.tar.gz"
[[VTKMinimal]]
arch = "powerpc64le"
cxxstring_abi = "cxx11"
git-tree-sha1 = "e48de2446f6b3d5fe0c32eedd194089d4fb24776"
libc = "glibc"
os = "linux"

    [[VTKMinimal.download]]
    sha256 = "4fde50a108a793080c6c5105ad13181e9e1d9b2a6e668f7f8a3f07d68ce3fc52"
    url = "https://github.com/j-fu/VTKMinimal_jll.jl/releases/download/VTKMinimal-v9.0.0+2/VTKMinimal.v9.0.0.powerpc64le-linux-gnu-cxx11.tar.gz"
[[VTKMinimal]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "3062486fe7970acb1c698da54988c1bc6eb9ab04"
os = "freebsd"

    [[VTKMinimal.download]]
    sha256 = "a1534e0f83998ab22d0d3e4a51a4b2a5851b239d870f17c6efca0a22e59bdc9a"
    url = "https://github.com/j-fu/VTKMinimal_jll.jl/releases/download/VTKMinimal-v9.0.0+2/VTKMinimal.v9.0.0.x86_64-unknown-freebsd11.1-cxx11.tar.gz"
