[[VTKMinimal]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "4e1a1e6c1f8ccb223f7c42352b223c4c1330368d"
libc = "glibc"
os = "linux"

    [[VTKMinimal.download]]
    sha256 = "7dc3aa4d96c526ea5a8b1ec801bcbe9957c0c0fdf34f0397ba1c67a843c0e3bc"
    url = "https://github.com/j-fu/VTKMinimal_jll.jl/releases/download/VTKMinimal-v9.0.0+0/VTKMinimal.v9.0.0.x86_64-linux-gnu-cxx11.tar.gz"
